---

# -------------------------------------
#
# Debian packages
#
# -------------------------------------
- name: snap | install packages
  apt:
    name: snapd
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - install

- name: install spotify
  community.general.snap:
    name:
      - spotify
