#!/usr/bin/env bash

echo "create asgard docker"

# **************************************
# cp utils
# **************************************
echo "- cp .bash_common"
cp ../docker-common/.bash_common .

echo "- cp .gitconfig"
cp ../../../git/files/.gitconfig .

# **************************************
# docker
# **************************************
echo "- Remove old docker_asgard_dev images"
docker rmi --force docker_asgard_dev

echo "- Build docker images"
docker build -t docker_asgard_dev .

echo "Finish Docker"
docker images

# **************************************
# rm tmp utils
# **************************************
echo "- rm tmp .bash_common"
rm -f .bash_common

echo "- rm tmp .gitconfig"
rm -f .gitconfig
