#!/bin/bash

set -e

echo "** Run set up"

# **************************************
# Install ansible
# **************************************
if which ansible > /dev/null; then
    echo "** ansible already installed"
else
    echo "** try to install ansible"
    sudo apt-get install -y ansible
fi

# **************************************
# Options
# **************************************
install_type=""
askbecomepass=""
askvaultpass=""
exclude="remote"
machine="laptop"


if [ -z "$1" ] && [ -z "$2" ]
then
    install_type="install"
    askbecomepass="--ask-become-pass"
    askvaultpass="--ask-vault-pass"
else
    if [[ "$1" == "update" ]]
    then
        echo "** only update config files"
        install_type="update-config"
        askvaultpass="--ask-vault-pass"
    else
        echo "** full installation"
        echo "** user password is required"
        install_type="install"
        askbecomepass="--ask-become-pass"
        askvaultpass="--ask-vault-pass"
    fi

    if [ -z "$2" ]
    then
        echo "** config in local mode: use links for config files"
    else
        echo "** config in ssh mode: use copy for config files"
        exclude="local"
        machine="$2"
    fi
fi

# **************************************
# Run ansible
# **************************************
HOST_OS=$(uname)

if [ "$HOST_OS" = 'Linux' ]; then
  ansible-playbook playbooks/"$machine".yml $askbecomepass $askvaultpass -t $install_type --skip-tags $exclude -v
else
  echo "** Unknown host OS: $HOST_OS"
  exit 1
fi

echo "** Finish set up"
trap - EXIT
