---

# -------------------------------------
#
# debian packages
#
# -------------------------------------
- name: install packages
  apt:
    name: [iptables, fail2ban, gufw, macchanger, chkrootkit, firejail, clamav, clamtk]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags: install


# -------------------------------------
#
# Common directories and config files
#
# -------------------------------------
- name: mac-changer | install
  shell: 'sudo ln -s {{role_path}}/files/mac-changer /etc/network/if-up.d/mac-changer'
  become: yes
  tags:
    - install
