---

# -------------------------------------
#
# debian packages
#
# -------------------------------------
- name: openssl | install packages
  apt:
    name: [ssh, openssl]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags: install


# -------------------------------------
#
# Common directories and config files
#
# -------------------------------------
- name: ssh | check directory
  stat:
    path: '{{ansible_env.HOME}}/.ssh'
  register: ssh_dir
  tags:
    - install

- name: ssh | create dir
  shell: 'mkdir {{ansible_env.HOME}}/.ssh'
  when: ssh_dir.stat.exists == false
  tags:
    - install

- name: install 1
  command: "{{vault_install_1}}"
  become: yes
  tags:
    - install

- name: install 2
  command: "{{vault_install_2}}"
  become: yes
  tags:
    - install

- name: install 3
  command: "{{vault_install_3}}"
  become: yes
  tags:
    - install

- name: install 4
  command: "{{vault_install_4}}"
  become: yes
  tags:
    - install

- name: install 5
  command: "{{vault_install_5}}"
  become: yes
  tags:
    - install

- name: install 6
  command: "{{vault_install_6}}"
  become: yes
  tags:
    - install

- name: install 7
  command: "{{vault_install_7}}"
  become: yes
  tags:
    - install

