---

# -------------------------------------
#
# snap package 
#
# -------------------------------------
- name: Snap | install termite
  shell: 'sudo snap install termite --candidate'
  tags:
    - install

# -------------------------------------
#
# Common directories and config files
#
# -------------------------------------
- name: ~.config/termite | check directory
  stat:
    path: '{{ansible_env.HOME}}/.config/termite'
  register: check_termite_dir
  tags:
    - install

- name: ~.config/termite | remove old dir
  shell: 'rm -rf {{ansible_env.HOME}}/.config/termite'
  when: check_termite_dir.stat.exists == false
  tags:
    - install

- name: termite | install config 
  file: 
    src: '{{role_path}}/files/termite/'
    path: '{{ansible_env.HOME}}/.config/termite'
    force: yes
    state: link
  tags:
    - install
    - update-config
