---

- name: termite | install dependencies
  apt:
    name: [git, g++, libgtk-3-dev, gtk-doc-tools, gnutls-bin, valac, intltool, libpcre2-dev, libglib3.0-cil-dev, libgnutls28-dev, libgirepository1.0-dev, libxml2-utils, gperf]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - install

- name: vte-ng | clone
  git:
    repo: https://github.com/thestinger/vte-ng.git
    dest: '{{ansible_env.HOME}}/dev/vte-ng'
    force: yes
  tags:
    - install

- name: vte-ng | export gtk-3.0
  shell: echo export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH"
  tags:
    - install

- name: vte-ng | make install
  shell: cd {{ansible_env.HOME}}/dev/vte-ng && ./autogen.sh && make && make install
  ignore_errors: yes
  become: yes
  tags:
    - install

- name: termite | clone
  git: 
    repo: https://github.com/thestinger/termite.git
    dest: '{{ansible_env.HOME}}/dev/termite'
    force: yes
  tags:
    - install

- name: termite | make install && config
  shell: cd {{ansible_env.HOME}}/dev/termite && make && make install && ldconfig
  ignore_errors: yes
  become: yes
  tags:
    - install

- name: termite | terminfo
  shell: mkdir -p /lib/terminfo/x
  become: yes
  tags:
    - install

- name: termite | config
  file: 
    src: /usr/local/share/terminfo/x/xterm-termite
    path: /lib/terminfo/x/xterm-termite
    force: yes
    state: link
  tags:
    - install

- name: termite | update-alternatives
  shell: update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/termite 60
  become: yes
  tags:
    - install

- name: termite | install config 
  file: 
    src: '{{role_path}}/files/termite/'
    path: '{{ansible_env.HOME}}/.config/termite'
    force: yes
    state: link
  tags:
    - install
    - update-config
