---

- name: fzf | Check is fzf installed
  shell: command -v fzf >/dev/null 2>&1
  register: is_fzf_exist
  ignore_errors: yes
  tags:
    - install

- name: fzf | clone
  git: 
    repo: https://github.com/junegunn/fzf.git
    dest: '{{ansible_env.HOME}}/.fzf'
    depth: 1
    force: yes
  when: is_fzf_exist.rc
  tags:
    - install

- name: fzf | install
  shell: 'cd {{ansible_env.HOME}}/.fzf && ./install'
  when: is_fzf_exist.rc
  tags:
    - install
