---

# -------------------------------------
#
# Debian packages
#
# -------------------------------------
- name: i3 | install packages
  apt:
    pkg:
    - vpnc-scripts
    - gettext
    - openconnect
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - install

# -------------------------------------
#
# Common directories and config files
#
# -------------------------------------
- name: openconnect | check .openconnect dir
  stat:
    path: '{{ansible_env.HOME}}/.openconnect'
  register: openconnect_folder
  tags: install

- name: tmux | create .openconnect dir
  file:
    path: '{{ansible_env.HOME}}/.openconnect'
    state: directory
    mode: "u=rwx,g=rx,o=rx"
  when: openconnect_folder.stat.exists == false
  tags: install
