---

# -------------------------------------
#
# Debian packages
#
# -------------------------------------
- name: rxvt-unicode | install packages
  apt:
    name: [rxvt-unicode]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags: install

# -------------------------------------
#
# Common directories and config files
#
# -------------------------------------
- name: .Xresources | install config files (symb link)
  file:
    src: '{{role_path}}/files/.Xresources'
    path: '{{ansible_env.HOME}}/.Xresources'
    force: yes
    state: link
  tags:
    - install
    - update-config

- name: ~/.urxvt/ext | check directory
  stat:
    path: '{{ansible_env.HOME}}/.urxvt/ext'
  register: check_urxvt_ext_dir
  tags:
    - install

- name: ~/.urxvt/ext | remove old dir
  shell: 'rm -rf {{ansible_env.HOME}}/.urxvt/ext'
  when: check_urxvt_ext_dir.stat.exists == true
  tags:
    - install

- name: ~/.urxvt/ext | install config
  file:
    src: '{{role_path}}/files/ext/'
    path: '{{ansible_env.HOME}}/.urxvt/ext'
    force: yes
    state: link
  tags:
    - install
    - update-config

#- name: reset config | urxvt
  #shell: xrdb ~/.Xresources
  #tags:
    #- install
    #- update-config
