---

# -------------------------------------
#
# Debian packages
#
# -------------------------------------
- name: rxvt-unicode | install packages
  apt:
    name: [rxvt-unicode]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags: install

# -------------------------------------
#
# Common directories and config files
#
# -------------------------------------
- name: .Xresources | install config files (symb link)
  file:
    src: '{{role_path}}/files/.Xresources'
    path: '{{ansible_env.HOME}}/.Xresources'
    force: yes
    state: link
  tags:
    - install
    - update-config

- name: reset config | urxvt
  shell: xrdb ~/.Xresources
  tags:
    - install
    - update-config
