---

- name: docker | install packages
  apt:
    name: docker.io
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - install

- name: docker | usermod
  shell: usermod -aG docker $USER
  become: yes
  tags:
    - install

- name: docker | restart service
  service:
    name: docker
    state: restarted    
  become: yes
  tags:
    - install
