---

- name: docker | gpg
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  tags:
    - install

- name: docker | add repo
  shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  tags:
    - install

- name: docker | apt update
  shell: sudo apt update
  tags:
    - install

- name: docker | install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags: install

- name: docker | install docker-ce
  apt:
    name: docker-compose
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags: install

- name: docker | usermod
  shell: usermod -aG docker $USER
  become: yes
  tags:
    - install

- name: docker | restart service
  service:
    name: docker
    state: restarted
  become: yes
  tags:
    - install

- name: java 11 profile | install
  file:
    src: '{{role_path}}/files/docker_java_11/.java_11_profile'
    path: '{{ansible_env.HOME}}/.java_11_profile'
    force: yes
    state: link
  tags:
    - install
    - update-config

- name: navitia profile | install
  file:
    src: '{{role_path}}/files/docker_navitia_dev/.navitia_profile'
    path: '{{ansible_env.HOME}}/.navitia_profile'
    force: yes
    state: link
  tags:
    - install
    - update-config
