#!/usr/bin/env bash

echo "create asgard docker"

# **************************************
# cp utils
# **************************************
echo "- cp .docker_common"
cp ../docker-common/.docker_common .

# **************************************
# docker
# **************************************
echo "- Remove old docker_asgard_dev images"
docker rmi --force docker_java_11

echo "- Build docker images"
docker build -t docker_java_11 .

echo "Finish Docker"
docker images

# **************************************
# rm tmp utils
# **************************************
echo "- rm tmp .bash_common"
rm -f .docker_common
