#!/usr/bin/env bash

echo "Create Navitia Bbst Docker"
echo "- Copy Jormun requirements.txt"
cp $HOME/dev/navitia/source/jormungandr/requirements_dev.txt .
cp $HOME/dev/navitia/source/jormungandr/requirements.txt .
cp $HOME/dev/navitia/requirements_pre-commit.txt .
echo "- Remove old docker_bbst_navitia_dev images"
docker rmi --force docker_bbst_navitia_dev
echo "- Build docker images"
docker build -t docker_bbst_navitia_dev .
echo "- Remove Jormun requirements.txt"
echo "Finish Docker"
rm -rf requirements*
docker images
