---

# -------------------------------------
#
# appimages
#
# -------------------------------------
- name: install neovim via AppImage ("universal" Linux package)
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: '{{item.binary_path}}/tools/nvim.appimage'
    mode: u+x
  with_items:
    - "{{vim_paths}}"
  tags:
    - install

# -------------------------------------
#
# Debian packages
#
# -------------------------------------
- name: neovim | install packages
  apt:
    name: [fonts-powerline, exuberant-ctags, ack-grep]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - install

# -------------------------------------
#
# Common directories and config files
#
# -------------------------------------
- name: ~/.vimrc | check file
  stat:
    path: '{{ansible_env.HOME}}/.vimrc'
  register: check_vimrc_file
  tags:
    - install

- name: remove old .vimrc
  shell: 'rm -f {{ansible_env.HOME}}/.vimrc'
  when: check_vimrc_file.stat.exists == true
  tags:
    - install

- name: ~.config | check directory
  stat:
    path: '{{ansible_env.HOME}}/.config'
  register: check_config_dir
  tags:
    - install

- name: ~.config | create dir
  shell: 'mkdir {{ansible_env.HOME}}/.config'
  when: check_config_dir.stat.exists == false
  tags:
    - install

- name: ~/.config/nvim | check dir
  stat:
    path: '{{ansible_env.HOME}}/.config/nvim'
  register: check_nvim_dir
  tags:
    - install

- name: remove old .config/nvim
  shell: 'rm -rf {{ansible_env.HOME}}/.config/nvim'
  when: check_nvim_dir.stat.exists == true
  tags:
    - install

- name: nvim | install nvim sources
  file:
    src: '{{item.vim_sources_path}}'
    path: '{{item.nvim_link_path}}'
    force: yes
    state: link
  with_items:
    - "{{vim_paths}}"
  tags:
    - install
    - update-config

- name: nvim | install vim sources
  file:
    src: '{{item.vim_sources_path}}'
    path: '{{item.vim_link_path}}'
    force: yes
    state: link
  with_items:
    - "{{vim_paths}}"
  tags:
    - install
    - update-config

- name: nvim | create vimrc link
  file:
    src: '{{item.vim_sources_path}}init.vim'
    path: '{{item.vimrc_link_path}}'
    force: yes
    state: link
  with_items:
    - "{{vim_paths}}"
  tags:
    - install
    - update-config

- name: ctags | install
  file:
    src: '{{role_path}}/files/.ctags'
    path: '{{ansible_env.HOME}}/.ctags'
    force: yes
    state: link
  tags:
    - install
    - update-config

- name: nvim | create plugged dir
  file:
    path: '{{item}}'
    state: directory
    mode: "u=rwx,g=rx,o=rx"
  with_items:
    - "{{plugged_dir}}"
  tags:
    - install

# -------------------------------------
#
# install plugin
#
# -------------------------------------
- name: install vim plugin
  shell: '{{ansible_env.HOME}}/bin/tools/nvim.appimage +PlugInstall +qall'
  tags:
    - install
