---

# -------------------------------------
#
# appimages
#
# -------------------------------------
- name: install neovim via AppImage ("universal" Linux package)
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: '{{item.binary_path}}/tools/nvim.appimage'
    mode: u+x
  with_items:
    - "{{vim_paths}}"
  tags:
    - install

# -------------------------------------
#
# Debian packages
#
# -------------------------------------
- name: neovim | install packages
  apt:
    name: [fonts-powerline, exuberant-ctags, ack-grep, ripgrep]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - install
