name: criteo
root: ~/
windows:
  - MAIN:
      root: ~
      layout: 83df,273x69,0,0[273x9,0,0,10,273x59,0,10,11]
      panes:
        - pane_with_multiple_commands:
            - htop
        - pane_with_multiple_commands:
            - clear
  - FMS:
      root: ~/dev/fleet-management-service
      panes:
          - #
  - FMS-UI:
      root: ~/dev/fleet-management-service/paas/fleet-management-service/Criteo.PaaS.FleetManager
      layout: a2ae,273x69,0,0{136x69,0,0,2,136x69,137,0,8}
      panes:
        - #
        - #
  - MSC:
      root: ~/dev/mesos-services-configuration
      layout: a2ae,273x69,0,0{136x69,0,0,2,136x69,137,0,8}
      panes:
          - #
          - #
  - RUNDECK:
      root: ~/dev/criteo-rundeck-resources
      layout: a2ae,273x69,0,0{136x69,0,0,2,136x69,137,0,8}
      panes:
          - #
          - #
