name: CI workflow

on:
    pull_request:

jobs:
    
    test_deploy:
        runs-on: ubuntu-latest
        container:
          image: ubuntu:18.04
        steps:
        - uses: actions/checkout@v2
        - name: install ansible
          run: |
            apt update
            apt install -y software-properties-common
            apt-add-repository --yes ppa:ansible/ansible
            apt install -y ansible 
        - name: ansible | install collection community.general
          run: ansible-galaxy collection install community.general
        - name: create vault file
          run: echo ${{secrets.VAULT_PASSWORD}} > vault_passwd
        - name: run install
          run: ./install
