---

- name: tmuxinator | install ruby packages
  apt:
    name: [ruby-full]
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"
  tags:
    - install

- name: tmuxinator | Install latest available version
  community.general.gem:
    name: tmuxinator
    version: 1.1.5
    state: present
  tags:
    - install

- name: tmuxinator | install config 
  file: 
    src: '{{role_path}}/files/tmuxinator/'
    path: '{{ansible_env.HOME}}/.config/tmuxinator'
    force: yes
    state: link
  tags:
    - install
    - update-config
